// Libellés des 81 sons (page d'écoute du 01/10/2026) — affichés dans /admin/sons-notifications.
export const SOUND_LABELS: Record<string, Record<string, string>> = {
  nuit: {
    "1": "Alarme bip-bip",
    "2": "Montée qui insiste",
    "3": "Klaxon de dépanneuse",
    "v1": "Son + voix homme : « Proposition de nuit ! Une mission t’attend. »",
    "v2": "Son + voix femme (belge) : « Proposition de nuit ! Une mission t’attend. »",
    "f1": "Réveil cartoon (cloche qui s’affole + boing)",
    "f2": "Charge de cavalerie (clairon)",
    "fv1": "Réveil cartoon (cloche qui s’affole + boing) + voix homme : « Debout champion ! Une dépanneuse a besoin de toi cette nuit ! »",
    "fv2": "Réveil cartoon (cloche qui s’affole + boing) + voix femme (belge) : « Debout champion ! Une dépanneuse a besoin de toi cette nuit ! »",
  },
  mission: {
    "1": "Ding-dong",
    "2": "Marimba montant",
    "3": "Cloche double",
    "v1": "Son + voix homme : « Nouvelle mission. »",
    "v2": "Son + voix femme (belge) : « Nouvelle mission. »",
    "f1": "Pièce de jeu vidéo",
    "f2": "Pouet-pouet de clown",
    "fv1": "Pièce de jeu vidéo + voix homme : « Allez hop, une nouvelle mission ! On y va ! »",
    "fv2": "Pièce de jeu vidéo + voix femme (belge) : « Allez hop, une nouvelle mission ! On y va ! »",
  },
  siabis: {
    "1": "Sirène courte",
    "2": "Triple bip grave",
    "3": "Gong d’autoroute",
    "v1": "Son + voix homme : « Demande Siabis couvert. »",
    "v2": "Son + voix femme (belge) : « Demande Siabis couvert. »",
    "f1": "Sifflet à coulisse qui monte",
    "f2": "Ta-da !",
    "fv1": "Sifflet à coulisse qui monte + voix homme : « Hé, le dispatch ! Un chauffeur demande Siabis couvert ! »",
    "fv2": "Sifflet à coulisse qui monte + voix femme (belge) : « Hé, le dispatch ! Un chauffeur demande Siabis couvert ! »",
  },
  parc: {
    "1": "Buzzer",
    "2": "Toc-toc-toc",
    "3": "Alerte descendante",
    "v1": "Son + voix homme : « Vérification au parc. »",
    "v2": "Son + voix femme (belge) : « Vérification au parc. »",
    "f1": "Toc-toc… boing !",
    "f2": "Point d’interrogation 8-bit",
    "fv1": "Toc-toc… boing ! + voix homme : « Toc toc toc ! Petite vérification au parc, s’il te plaît. »",
    "fv2": "Toc-toc… boing ! + voix femme (belge) : « Toc toc toc ! Petite vérification au parc, s’il te plaît. »",
  },
  talkie: {
    "1": "Bip radio",
    "2": "Grésillement + bip",
    "3": "Double clic talkie",
    "v1": "Son + voix homme : « Message talkie. »",
    "v2": "Son + voix femme (belge) : « Message talkie. »",
    "f1": "Petit robot qui bavarde",
    "f2": "Kazoo « hého »",
    "fv1": "Petit robot qui bavarde + voix homme : « Allô, allô ! Un collègue te parle ! »",
    "fv2": "Petit robot qui bavarde + voix femme (belge) : « Allô, allô ! Un collègue te parle ! »",
  },
  info: {
    "1": "Carillon court",
    "2": "Petit succès",
    "3": "Pop",
    "v1": "Son + voix homme : « C’est validé. »",
    "v2": "Son + voix femme (belge) : « C’est validé. »",
    "f1": "Power-up de jeu vidéo",
    "f2": "Clin d’œil (pop + ding)",
    "fv1": "Power-up de jeu vidéo + voix homme : « Et voilà, c’est dans la poche ! »",
    "fv2": "Power-up de jeu vidéo + voix femme (belge) : « Et voilà, c’est dans la poche ! »",
  },
  escalade: {
    "1": "Sirène pompier",
    "2": "Alarme continue",
    "3": "Cloche d’alerte rapide",
    "v1": "Son + voix homme : « Urgent ! Personne n’a pris la mission. »",
    "v2": "Son + voix femme (belge) : « Urgent ! Personne n’a pris la mission. »",
    "f1": "Wee-woo cartoon",
    "f2": "Clairon d’urgence ×2",
    "fv1": "Wee-woo cartoon + voix homme : « Alerte générale ! Personne n’a pris la mission, à toi de jouer ! »",
    "fv2": "Wee-woo cartoon + voix femme (belge) : « Alerte générale ! Personne n’a pris la mission, à toi de jouer ! »",
  },
  check: {
    "1": "Clé à molette (cling métal)",
    "2": "Deux notes graves",
    "3": "Marimba descendant",
    "v1": "Son + voix homme : « Nouveau rapport véhicule. »",
    "v2": "Son + voix femme (belge) : « Nouveau rapport véhicule. »",
    "f1": "Clé à molette + boing",
    "f2": "Roulement de tambour + cymbale",
    "fv1": "Clé à molette + boing + voix homme : « Nouveau rapport véhicule : le chauffeur a fait ses devoirs ! »",
    "fv2": "Clé à molette + boing + voix femme (belge) : « Nouveau rapport véhicule : le chauffeur a fait ses devoirs ! »",
  },
  repare: {
    "1": "Succès joyeux",
    "2": "Ding clair",
    "3": "Accord majeur",
    "v1": "Son + voix homme : « Réparé ! Merci pour ton signalement. »",
    "v2": "Son + voix femme (belge) : « Réparé ! Merci pour ton signalement. »",
    "f1": "Fanfare de victoire",
    "f2": "Niveau terminé 8-bit",
    "fv1": "Fanfare de victoire + voix homme : « Et hop, c’est réparé ! Merci champion ! »",
    "fv2": "Fanfare de victoire + voix femme (belge) : « Et hop, c’est réparé ! Merci champion ! »",
  },
}
